// Generated by dts-bundle v0.7.3

declare module 'cssville' {
    import { IGenerator } from "cssville/IGenerator";
    export default class Cssville {
        static prefixValueMap: Map<string, string>;
        static generators: IGenerator[];
        static getCss(classes?: string[]): string;
    }
}

declare module 'cssville/IGenerator' {
    import { CssClassData } from "cssville/data/cssClassData";
    export interface IGenerator {
        name: string;
        postfixValuesMap: Map<string, string[]>;
        cssData: CssClassData[];
        generate(prefix: string, classes: string[]): string;
    }
}

declare module 'cssville/data/cssClassData' {
    export class CssClassData {
        constructor(className: string, cssProperties: string[], postfixArray: string[], postfixValuesMap?: Map<string, string[]>);
        className: string;
        cssProperties: string[];
        postfixValuesMap: Map<string, string[]>;
        getCss(prefix: string, classes: string[]): string;
    }
}

